version: "3"

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      AILINGBOT_CHANNEL__NAME: ${AILINGBOT_CHANNEL__NAME}
      AILINGBOT_CHANNEL__TOKEN: ${AILINGBOT_CHANNEL__TOKEN}
      AILINGBOT_CHANNEL__AES_KEY: ${AILINGBOT_CHANNEL__AES_KEY}
      AILINGBOT_CHANNEL__VERIFICATION_TOKEN: ${AILINGBOT_CHANNEL__VERIFICATION_TOKEN}
      AILINGBOT_CHANNEL__CORPID: ${AILINGBOT_CHANNEL__CORPID}
      AILINGBOT_CHANNEL__CORPSECRET: ${AILINGBOT_CHANNEL__CORPSECRET}
      AILINGBOT_CHANNEL__AGENTID: ${AILINGBOT_CHANNEL__AGENTID}
      AILINGBOT_CHANNEL__APP_ID: ${AILINGBOT_CHANNEL__APP_ID}
      AILINGBOT_CHANNEL__APP_SECRET: ${AILINGBOT_CHANNEL__APP_SECRET}
      AILINGBOT_UVICORN_HOST: "0.0.0.0"
      AILINGBOT_UVICORN_PORT: 8080
      AILINGBOT_POLICY__LLM__OPENAI_API_KEY: ${AILINGBOT_POLICY__LLM__OPENAI_API_KEY}
    restart: unless-stopped
    command: poetry run ailingbot channel serve
